# Generated by Django 5.0.6 on 2024-06-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taverna', '0002_rename_favotire_game_user_favorite_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_table',
            name='max_players',
            field=models.PositiveIntegerField(),
        ),
    ]
